alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: steve
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: steve-prod
region: tor
services:
- name: steve
  image:
    registry_type: "DOCR"
    registry: ""
    repository: "steve-prod"
    tag: "latest"
  envs:
  - key: DB_IP
    scope: RUN_TIME
    value: mysql-do-user-18968842-0.k.db.ondigitalocean.com
  - key: DB_PORT
    scope: RUN_TIME
    value: "25060"
  - key: DB_SCHEMA
    scope: RUN_TIME
    value: steve_prod
  - key: DB_USER
    scope: RUN_TIME
    value: steve_prod
  - key: DB_PASSWORD
    scope: RUN_TIME
    type: SECRET
    value: EV[1:rAI2b2eR2qi6J8hNQLentncj6+iIVC90:gE7SMqXSxopY22rAYlQjsRrgzLiPcx48BqVBwLR6ly2dvpCTZrgQRw==]
  - key: AUTH_USER
    scope: RUN_TIME
    value: admin
  - key: AUTH_PASSWORD
    scope: RUN_TIME
    type: SECRET
    value: EV[1:F8xt/anr99CsfLpWcbHAN5u5jX3R7qEJ:0gcYe/ESTtfKxLReCZllsbNXiSoheXo=]
  - key: WEBAPI_VALUE
    scope: RUN_TIME
    type: SECRET
    value: EV[1:3/IZYWJszyT2TRFsQqg8OiBkMp2cfqs+:Hgwulr/p33EjWkbEY5Q79hCa2fHrKAU=]
  http_port: 4443
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  internal_ports:
  - 8080
